### ISSUE TITLE
BOB theme

### ISSUE THREAD

**Issue by tomjeatt** [interlay/ui#59]
### Description

Implement BOB theme properly

### Problem Statement/Justification

...

### Proposed Solution or API

...

**Comment by danielsimao** [comment]
TODOs

- [ ] Button
- [ ] Input
- [ ] Drawer
- [ ] Alert
- [ ] Breadcrumbs
- [ ] Card
- [ ] Dialog
- [ ] Divider
- [ ] Field
- [ ] Flex
- [ ] HelperText
- [ ] Label
- [ ] List
- [ ] Modal
- [ ] NumberInput
- [ ] ProgressBar
- [ ] Radio
- [ ] Select
- [ ] Spinner
- [ ] Switch
- [ ] Table
- [ ] Tabs
- [ ] Text
- [ ] TextArea
- [ ] TokenInput
- [ ] Tooltip
- [ ]
